#!/usr/bin/env sh

#sudo yabai --load-sa
#yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add label="Float non-resizable windows" event=window_created action="yabai -m query --windows --window \$YABAI_WINDOW_ID | grep -q 'is-floating.*false' && yabai -m query --windows --window \$YABAI_WINDOW_ID | grep -q 'can-resize.*false' && sleep 0.1 && yabai -m window --toggle float && skhd -k 'fn + ctrl - c'"

yabai -m signal --add event=window_created action="sh ~/.config/yabai/single_window.sh"
yabai -m signal --add event=window_destroyed action="sh ~/.config/yabai/single_window.sh"
yabai -m signal --add event=window_minimized action="sh ~/.config/yabai/single_window.sh"
yabai -m signal --add event=window_deminimized action="sh ~/.config/yabai/single_window.sh"
yabai -m signal --add event=space_changed action="sleep 1 && sh ~/.config/yabai/single_window.sh"
#yabai -m signal --add event=display_changed action="sh ~/.config/yabai/single_window.sh"

yabai -m signal --add event=window_destroyed action="/usr/bin/osascript -l JavaScript ~/.config/yabai/autoquit.jsx"
yabai -m signal --add event=window_destroyed action="sh ~/.config/yabai/change_space.sh"

yabai -m config \ #external_bar all:40:0 \
  mouse_follows_focus on \
  focus_follows_mouse autoraise \
  window_zoom_persist on \
  window_placement second_child \
  window_shadow float \
  window_opacity on \
  window_opacity_duration 0.2 \
  window_insertion_point focused \
  active_window_opacity 1.0 \
  normal_window_opacity 0.8 \
  window_animation_duration 0.5 \
  window_animation_easing ease_out_quint \
  insert_feedback_color 0xff9dd274 \
  split_ratio 0.50 \
  auto_balance off \
  mouse_modifier fn \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap \
  \
  top_padding 7 \
  bottom_padding 8 \
  left_padding 8 \
  right_padding 8 \
  window_gap 7

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor|Tips|FaceTime)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension|Feature Flag)s|AutoFill|Se(arch|curity)|Privacy|Advanced|Developer)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off
yabai -m rule --add label="Obsidian splash screen" app="^(Obsidian)" title="^(Obsidian)$" manage=off
yabai -m rule --add app="^(Notes)" title="^(.* Settings)$" manage=off

yabai -m config layout bsp

echo "yabai configuration loaded.."
