source = ~/.config/omarchy/current/theme/hyprlock.conf

general {
    hide_cursor = false
    ignore_empty_input = true
}

background {
    monitor =
    color = $color
    path = ~/.config/omarchy/current/background
    blur_passes = 3
}

animations {
    enabled = true
}

image {
    monitor =
    path = ~/Downloads/sf-power.png
    path = ~/.dotfiles/hypr/.config/hypr/hyprlock/sf-symbols-png/SF Symbols - 5924.png
    onclick = omarchy-system-shutdown
    border_size = 2
    border_color = rgba(255, 255, 255, 0)
    size = 32
    rounding = -1
    position = -80, -47%
    halign = center
    valign = center
}

image {
    path = ~/.dotfiles/hypr/.config/hypr/hyprlock/sf-symbols-png/SF Symbols - 5933.png
    path = ~/.dotfiles/hypr/.config/hypr/hyprlock/sf-symbols-png/SF Symbols - 0257.png
    onclick = omarchy-system-logout
    border_size = 2
    border_color = rgba(255, 255, 255, 0)
    size = 32
    rounding = -1
    position = 80, -47%
    halign = center
    valign = center
}

image {
    path = ~/.dotfiles/hypr/.config/hypr/hyprlock/sf-symbols-png/SF Symbols - 5935.png
    onclick = omarchy-system-reboot
    border_size = 2
    border_color = rgba(255, 255, 255, 0)
    size = 32
    rounding = -1
    position = 0, -47%
    halign = center
    valign = center
}

# Date display
label {
    monitor =
    #text = cmd[update:1000] echo -e "$(date +"%A, %e %B %Y")"
    #text = cmd[update:1000] echo -e "$(LC_TIME=ja_JP.UTF-8 date +"%x (%a)")"
    text = cmd[update:1000] echo -e "$(LC_TIME=en_GB.UTF-8 date +"%A,%e %B")"
    color = rgba(216, 222, 233, 0.90)
    font_size = 25
    font_family = SF Pro Text
    font_family = .SF NS Rounded
    position = 0, 625
    halign = center
    valign = center
}

# Time display
label {
    monitor =
    text = $TIME
    color = rgba(216, 222, 233, 0.80)
    font_size = 120
    font_size = 180
    font_family = .SF NS Rounded Medium
    position = 0, 485
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] [ \"$(upower -i $(upower -e | grep BAT) | grep state | sed 's/^.*state:\W*//g')\" = \"discharging\" ] && echo "   $(omarchy-battery-remaining)%" || echo ""
    color = rgba(216, 222, 233, 0.90)
    font_size = 25
    font_family = SF Pro Text
    font_family = .SF NS Rounded
    position = 0, 350
    halign = center
    valign = center
}

#image {
#    path = ~/.config/hypr/hyprlock/profile.png
#    border_size = 2
#    border_color = rgba(255, 255, 255, 0)
#    size = 160
#    rounding = 0
#    position = 0, -30%
#    halign = center
#    valign = center
#}

#label {
#    monitor =
#    text = cmd[] echo -e "\u00A0"; cat <~/.local/share/omarchy/logo.txt; omarchy-version
#    color = rgba(216, 222, 233, 0.10)
#    font_family = FiraCode Nerd Font
#    halign = center
#    valign = center
#}

label {
    monitor =
    text = cmd[] echo -e ""
    color = rgba(216, 222, 233, 0.90)
    font_size = 25
    font_family = Noto Sans
    position = 0, -500
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 650, 100
    position = 0, -600
    halign = center
    valign = center

    inner_color = rgba(216, 222, 233, 0.2) #$inner_color
    outer_color = $outer_color
    outline_thickness = 4 #4

    font_size = 25
    font_family = SF Pro Text
    font_family = .SF NS Rounded
    font_color = rgba(216, 222, 233, 0.90) #$font_color

    placeholder_text = <span> Enter Password 󰈷 </span>
    placeholder_text = $FPRINTPROMPT 
    check_color = $check_color
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    rounding = -1
    shadow_passes = 0
    fade_on_empty = true
}

auth {
    fingerprint:enabled = true
}
