# Modal/floating windows should stand out more.
layerrule = no_anim off, dim_around on, animation popin, match:namespace walker
windowrule = dim_around on, animation popin, match:float true, match:class negative:Snapmaker_Orca

# Music
# windowrule = float off, workspace special:scratchpad, match:class (.*music.apple.com.*|.*cliamp.*)

# Zen browser
windowrule = fullscreen_state 0 2, match:class zen

# Deigning apps
windowrule = workspace 3, match:class (org.openscad.openscad|Snapmaker_Orca|chrome-192.168.8.163__-Default|chrome-printables.com__-Default)
windowrule = float on, workspace 3, match:class org.openscad.openscad, match:initial_title negative:.*\.scad.*

# Coding apps
# windowrule = workspace 2, match:class org.omarchy.nvim

# Writing apps
windowrule = workspace 4, match:class (obsidian|Typora)

# If there's only one window, we don't need the coloured "in focus" border.
windowrule = opacity 1.25, decorate off, match:workspace w[1], match:class negative:Snapmaker_Orca

# Make fullscreen windows opaque
windowrule = opacity 1.25, match:fullscreen_state_client 2

# Float LocalSend and fzf file picker
windowrule = float off, workspace special:scratchpad, match:class (Share|localsend)
#windowrule = center on, match:class (Share|localsend)

# Apps to keep opaque
windowrule = tag -default-opacity, match:class (org.gnome.Connections|.*youtube.*)
windowrule = opacity 1.25, match:class (org.gnome.Connections|.*youtube.com.*)

# ARCHIVE FOR LATER EXAMPLES

# windowrule = decorate off, rounding 0, match:workspace Coding, match:class org.omarchy.nvim
# windowrule = decorate off, rounding 0, match:workspace Coding, match:tag terminal*
# windowrule = decorate off, rounding 0, match:workspace Coding, match:title OpenCode

# workspace = w[1], gapsout:0
# windowrule = decorate off, rounding 0, match:workspace w[1], match:class org.omarchy.nvim
# windowrule = decorate off, rounding 0, match:workspace w[1], match:tag terminal*
