# dwindle:force_split = 1

general:gaps_out = 4, 5, 5, 5
general:gaps_in = 2

# layout:single_window_aspect_ratio = 1 1

decoration {
  rounding = 12
#  rounding_power = 1 #4
#  active_opacity = 0.8
#  inactive_opacity = 0.8
#  fullscreen_opacity = 0.8
  blur:size = 8
  blur:passes = 3
}
