# Mac-like bindings
bindd = SUPER, Q, Close window, killactive
bindd = CONTROL_L, BACKSPACE, Delete forward, sendshortcut, , Delete, activewindow
bindd = CONTROL, 3, Mac GB layout hash key, sendshortcut, MOD5, 3, activewindow

# Browser
unbind = SUPER, L
bindd  = SUPER, L, Select address bar in browser, sendshortcut, CTRL, L, activewindow
bindd  = SUPER, R, Refresh current tab, sendshortcut, CTRL, R, activewindow
unbind = SUPER, T
bindd  = SUPER, T, Toggle window tiling / New browser tab, exec, ~/.config/hypr/bin/app-specific-bindings CTRL,T "dispatch togglefloating"
bindd  = SUPER SHIFT, T, Toggle window floating/tiling, togglefloating
unbind = SUPER, W
bindd  = SUPER, W, Close window or browser tab, exec, ~/.config/hypr/bin/app-specific-bindings
bindd  = SUPER, Z, Unclose browser tab, exec, ~/.config/hypr/bin/app-specific-bindings "CTRL SHIFT,T" clients
bindd  = CTRL, bracketleft, Next tab, sendshortcut, CTRL&SHIFT, TAB, activewindow
bindd  = CTRL, bracketright, Previous tab, sendshortcut, CTRL, TAB, activewindow
bindd  = SUPER SHIFT, H, Go to Home in Web Apps, sendshortcut, ALT, HOME, activewindow

bindd  = SUPER, M, Minimise, movetoworkspacesilent, special:minimize
unbind = SUPER CONTROL, N
bindd  = SUPER CONTROL, N, Toggle nightlight, exec, ~/.config/hypr/bin/custom-toggle-nightlight
bindd = SUPER CONTROL ALT, SPACE, Cycle through theme backgrounds, exec, omarchy-theme-bg-next

unbind = ,XF86MonBrightnessUp
bindeld = ,XF86MonBrightnessUp, Brightness up, exec, awk '{g=$1-0.018; if(g>0.36)g=0.36; if(g<0)g=0; printf "%.3f\n", g}' /tmp/als-gamma > /tmp/als-gamma.tmp && mv /tmp/als-gamma.tmp /tmp/als-gamma && omarchy-swayosd-brightness $(awk -v f="$(cat /tmp/als-gamma)" 'BEGIN { printf (0.36 - f) / (0.36 - 0.0) * 100 }')
unbind = ,XF86MonBrightnessDown
bindeld = ,XF86MonBrightnessDown, Brightness down, exec, awk '{g=$1+0.018; if(g>0.36)g=0.36; if(g<0)g=0; printf "%.3f\n", g}' /tmp/als-gamma > /tmp/als-gamma.tmp && mv /tmp/als-gamma.tmp /tmp/als-gamma && omarchy-swayosd-brightness $(awk -v f="$(cat /tmp/als-gamma)" 'BEGIN { printf (0.36 - f) / (0.36 - 0.0) * 100 }')

bindeld = SHIFT,XF86AudioMute, Mute microphone, exec, omarchy-audio-input-mute
#pactl set-source-mute @DEFAULT_SOURCE@ toggle

# Apps
unbind = SUPER SHIFT, M
bindd  = SUPER SHIFT, M, Music TUI, exec, omarchy-launch-or-focus-tui cliamp
unbind = SUPER SHIFT ALT, M
#bindd  = SUPER SHIFT ALT, M, Music, exec, omarchy-launch-or-focus spotify
unbind = SUPER SHIFT, A
unbind = SUPER SHIFT ALT, A
unbind = SUPER SHIFT CONTROL, G
unbind = SUPER SHIFT ALT, G
unbind = SUPER SHIFT, P
unbind = SUPER SHIFT, X
unbind = SUPER SHIFT ALT, X

source = ~/.config/hypr/custom-tiling.conf

# unbind = SUPER, 1
# unbind = SUPER SHIFT, 1
# bindd = SUPER, 1, Switch to browser workspace, workspace, name:Browsing
# bindd = SUPER SHIFT, 1, Move window to browser workspace, movetoworkspace, name:Browsing
# 
# unbind = SUPER, 2
# unbind = SUPER SHIFT, 2
# bindd = SUPER, 2, Switch to Coding workspace, workspace, name:Coding
# bindd = SUPER SHIFT, 2, Move window to Coding workspace, movetoworkspace, name:Coding
# 
# unbind = SUPER, 3
# unbind = SUPER SHIFT, 3
# bindd = SUPER, 3, Switch to Designing workspace, workspace, name:Designing
# bindd = SUPER SHIFT, 3, Move window to Designing workspace, movetoworkspace, name:Designing
# 
# unbind = SUPER, 4
# unbind = SUPER SHIFT, 4
# bindd = SUPER, 4, Switch to Writing workspace, workspace, name:Writing
# bindd = SUPER SHIFT, 4, Move window to Writing workspace, movetoworkspace, name:Writing
