# dwindle {
#   force_split = 1
# }

# general {
#   gaps_out = 8
#   gaps_in = 4
# }

decoration {
#  rounding = 12
#  rounding_power = 1 #4
 active_opacity = 0.8
 inactive_opacity = 0.8
#  fullscreen_opacity = 0.8
 blur:size = 8
 blur:passes = 3
}
