# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf

# Add any other personal Hyprland configuration below
# windowrule = workspace 5, match:class qemu

# Modal/floating windows should stand out more.
layerrule = no_anim off, dim_around on, animation popin, match:namespace walker
windowrule = dim_around on, animation popin, match:float true, match:class negative:Snapmaker_Orca

# OpenSCAD and OrcaSlicer rules
windowrule = workspace name:Designing, match:class org.openscad.openscad
windowrule = float on, workspace name:Designing, match:class org.openscad.openscad, match:initial_title negative:.*\.scad.*
windowrule = workspace name:Designing, match:class Snapmaker_Orca

# Writing workspace
windowrule = workspace name:Writing, match:class Typora

# If there's only one window, we don't need the coloured "in focus" border.
windowrule = decorate off, match:workspace w[1]

# Float LocalSend and fzf file picker
windowrule = float off, match:workspace special:scratchpad# match:class (Share|localsend)
#windowrule = center on, match:class (Share|localsend)

# Make Connections (VNC) use opaque background
windowrule = tag -default-opacity, match:class org.gnome.Connections
windowrule = opacity 1.25, match:class org.gnome.Connections

# ARCHIVE FOR LATER EXAMPLES

# windowrule = decorate off, rounding 0, match:workspace Coding, match:class org.omarchy.nvim
# windowrule = decorate off, rounding 0, match:workspace Coding, match:tag terminal*
# windowrule = decorate off, rounding 0, match:workspace Coding, match:title OpenCode

# workspace = w[1], gapsout:0
# windowrule = decorate off, rounding 0, match:workspace w[1], match:class org.omarchy.nvim
# windowrule = decorate off, rounding 0, match:workspace w[1], match:tag terminal*
