[General]
lastOpenDirName=/home/ted/Designs/semiotic-standard
recentFileList=/home/ted/Designs/semiotic-standard/main.scad

[3dview]
colorscheme=tokyo-night

[design]
autoReload=true

[editor]
syntaxhighlight=Dracula

[view]
hide3DViewToolbar=false
hideConsole=true
hideCustomizer=true
hideEditor=true
hideEditorToolbar=false
hideErrorLog=true
orthogonalProjection=true
showAxes=false
showEdges=false
showScaleProportional=true
